resources:
  repositories:
  - repository: az-aib-common # The name used to reference this repository in the checkout step
    type: github
    endpoint: Azure
    name: kevinpz/az-aib-common@az-aib-common

variables:
- template: common-variables.yml

# Auto trigger when changes on main
trigger:
  branches:
    include:
      - main

stages:
# Register the providers for the subscription
- stage: Prereq
  jobs:
  - job: Prereq
    steps:
      - task: AzureCLI@2
        inputs:
          workingDirectory: prereq
          azureSubscription: '$(sc_name)'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          arguments: '$(subscription_id)'
          scriptPath: './prereq/register_provider.sh'

# Deploy the base for the Azure Image Builder service
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
      # Download Terraform binary
      - task: TerraformInstaller@0
        displayName: install terraform
        inputs:
          terraformVersion: latest
      # Init Terraform backend and download providers
      - task: TerraformCLI@0
        displayName: 'terraform init'
        inputs:
          workingDirectory: terraform
          command: init
          # Configure the backend to store the .tfstate file
          backendType: azurerm
          backendServiceArm: '$(sc_name)'
          backendAzureRmSubscriptionId: '$(subscription_id)'
          backendAzureRmResourceGroupName: '$(stg_rg_name)'
          backendAzureRmStorageAccountName: '$(stg_name)'
          backendAzureRmContainerName: '$(stg_container_name)'
          backendAzureRmKey: '$(System.TeamProject)/$(Build.Repository.Name).tfstate'
      # Deploy Terraform ressources
      - task: TerraformCLI@0
        displayName: 'terraform apply'
        inputs:
          workingDirectory: terraform
          command: apply
          environmentServiceName: '$(sc_name)'
          providerAzureRmSubscriptionId: '$(subscription_id)'
          commandOptions: '-var "location=$(location)" -var "rg_name=$(rg_name)" -var "id_name=$(id_name)" -var "gallery_name=$(gallery_name)"'